
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_service?createDatabaseIfNotExist=true
    username: root
    password: JayaminaV18738
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
  application:
    name: orderservice
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:9190/oauth/check_token
    client:
      client-id: mobile
      client-secret: pin